version: '3.8'
services:
  backend:
    build:
      context: ./backend
    ports:
      - "5001:5001"
    env_file:
      - ./backend/.env
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./my-app
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5001

  mongodb:
    image: mongo:5
    container_name: indramayu-db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
